language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python bootstrap.py; bin/buildout


# command to run tests, e.g. python setup.py test
script: ./bin/nosetests -v